config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord

  validates :name, presence: true, uniqueness: true

  has_many :group_users, dependent: :delete_all
  has_many :users, through: :group_users
  has_many :messages

  scope :desc, -> { order("groups.updated_at DESC") }

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :text_or_image, :group_id, :user_id, presence:true

  belongs_to :group
  belongs_to :user

  private

  def text_or_image
    text.presence || image.presence
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys:[:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups.desc
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice: "グループを作成しました。"
    else
      flash[:alert]="グループ作成に失敗しました。"
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_messages_path(params[:id]), notice: "グループを更新しました。"
    else
      flash[:alert] = "グループ作成に失敗しました"
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_group, only: [:index, :create]
  before_action :set_groups, only: [:index, :create]

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(params[:group_id]) }
        format.json
      end
    else
      flash.now[:alert]="メッセージの送信に失敗しました。"
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_groups
    @groups = current_user.groups.desc
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    current_user.update(user_params)
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for(@group) do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2
        = @group.errors.count
        件のエラーが発生しました。
        %ul
          - @group.errors.full_messages.each do |msg|
            %li
              = msg
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_name"} グループ名
    .chat-group-form__field--right
      = f.text_field :name, placeholder: 'グループ名を入力してください', class: "chat-group-form__input"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_add_chat-member"}チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input{type: "text", placeholder: "追加したいユーザ名を入力してください", class: "chat-group-form__input", id: "user-search-field"}
      .user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_chat-member"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users

  -# collection_checkboxesでの実装はコメントアウトすることとする
  -#     .check_box
  -#       = f.collection_check_boxes(:user_ids, User.all, :id, :name) do |b|
  -#         = b.label { b.check_box + b.text }

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit :commit, value: "Save", class: "chat-group-form__action-btn", disable_width: "Save"

app/views/groups/_side.html.haml
.side
  .sideUser
    %h2.sideUser__name
      = current_user.name
    %ul.sideUser__nav
      %li
        = link_to new_group_path do
          %i.fa.fa-pencil-square-o
      %li
        = link_to edit_user_path(current_user.id) do
          %i.fa.fa-cog
  .sideGroup
    - if @groups
      - @groups.each do |group|
        .sideGroup__box
          = link_to group_messages_path(group.id) do
            .sideGroup__boxName
              = group.name
            .sideGroup__boxMessage
              = group.message_last

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: "form", local: @group

app/views/groups/index.html.haml
= render partial:"side", local: @groups

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: "form", local: @group

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Chatspace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_chat.html.haml
.mainChat__box
  .mainChat__boxUpper
    .mainChat__boxName
      = chat.user.name
    .mainChat__boxTime
      = chat.created_at.strftime('%Y/%m/%d %H:%M:%S')
  .mainChat__boxMessage{data: {chatid: "#{chat.id}"}}
    - if chat.image.blank?
      = chat.text
    - else
      = image_tag chat.image_url(:thumb)

app/views/messages/index.html.haml
.wrap
  = render partial:"groups/side", local: @groups
  .main
    .mainHeader
      .mainHeader__title
        = @group.name
      .mainHeader__member
        %ul
          %label Member：
          - @group.users.each do |member|
            %li
              = member.name
      .mainHeader__edit
        = link_to edit_group_path(@group) do
          Edit
    .mainChat
      = render partial: "chat", collection: @messages
    .mainForm
      = form_for([@group, @message], :html => {class: "mainForm__wrap"}) do |f|
        = f.text_field :text, placeholder: 'type a message', value: "", id: "mainForm__input", class: "mainForm__input"
        .mainForm__image
          %label.mainForm__imageUpload
            %i.fa.fa-picture-o
            = f.file_field :image, id: "imageUpload", class: "hidden"
        .cancelBtn
          %i.fa.fa-times
        = button_tag type: "submit", class: "mainForm__btn" do
          Send

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", root_path, class: 'btn'
    .account-page__inner--right.user-form
      = form_for current_user do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'